from collections.abc import Hashable
from typing import Generic, Iterable, TypeVar

T = TypeVar('T', bound=Hashable)

class DisjointSet(Generic[T]):
    parent: dict[T, T]
    size: dict[T, int]
    def __init__(self) -> None: ...
    def make_set(self, x: T) -> None: ...
    def find(self, x: T) -> T: ...
    def union(self, x: T, y: T) -> None: ...
    def same_set(self, x: T, y: T) -> bool: ...
    def make_set_many(self, elements: Iterable[T]) -> None: ...
    def find_many(self, elements: Iterable[T]) -> tuple[T, ...]: ...
    def union_many(self, elements: Iterable[T]) -> None: ...
    def same_set_many(self, elements: Iterable[T]) -> bool: ...
    def __len__(self) -> int: ...
    def get_element_count(self) -> int: ...
    def get_component_count(self) -> int: ...
    def get_component_size(self, x: T) -> int: ...
